source ~/.vim/scripts/plugins.vim
source ~/.vim/scripts/mappings.vim

" Colorscheme and customization -------------{{{
set t_Co=256
" colorscheme gruvbox
" colorscheme github
colorscheme solarized
command AirlineTheme solarized
set background=dark

augroup foldSpaceOrientedSyntax
  autocmd!
  autocmd BufNewFile,BufReadPost *.{coffee,yml} setl foldmethod=indent
augroup END

augroup cursorLineAndColumn
  autocmd!
  autocmd WinLeave * set nocursorline nocursorcolumn
  " autocmd WinEnter * set cursorline cursorcolumn
  " set cursorcolumn cursorline
augroup END

augroup toggleInsertMode " {{{
  autocmd!
  " autocmd insertEnter * hi CursorColumn ctermbg=darkred
  " autocmd insertLeave * hi CursorColumn ctermbg=233
augroup END
"}}}

augroup trailingWhiteSpace
  autocmd!
  autocmd BufWritePre * try | %s/ \+$// | catch | | endtry
augroup END

set numberwidth=3
set number

set colorcolumn=80
set list listchars=tab:›≈,trail:░,eol:¬

set laststatus=2

set autoindent

" Vimscript file settings --------------------------{{{
augroup filetype_vim
  autocmd!
  autocmd FileType vim setlocal foldmethod=marker
augroup END
" }}}

set t_ut=

hi NonText ctermbg=NONE

" hi CursorColumn cterm=NONE ctermbg=233
" hi CursorLine   cterm=NONE ctermbg=234

" disable fold for now
set nofoldenable

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smarttab

set shell=/bin/sh

set hlsearch
set incsearch
set backspace=2

let g:airline#extensions#tabline#enabled = 1

let g:ctrlp_use_caching = 0
set grepprg=ag\ --nogroup\ --nocolor
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

" Hilight search in Monokai HACK
hi Search ctermbg=44B449

let g:ctrlp_show_hidden = 1

let g:ruby_heredoc_syntax_filetypes = {
  \"yaml" : {
  \     "start" : "YAML"
  \}
\}


" embear/vim-localvimrc
let g:localvimrc_ask=0
let g:localvimrc_sandbox=0

" scrooloose/syntastic
let g:syntastic_cpp_compiler="clang++"
let g:syntastic_cpp_compiler_options="-std=c++11 -stdlib=libc++ -Weverything -Wno-c++98-compat"
let g:syntastic_cpp_check_header=1
